In [1]:
import pandas as pd
import numpy as np


In [2]:
import matplotlib.pyplot as plt

In [3]:
x=pd.read_csv("matches.csv")
x

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
1,2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
2,3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
3,4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
4,6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0.0,4.0,...,Match Report,NaN,8.0,1.0,17.4,0.0,0.0,0.0,2021,Sheffield United
1385,39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0.0,2.0,...,Match Report,NaN,7.0,0.0,11.4,1.0,0.0,0.0,2021,Sheffield United
1386,40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1.0,0.0,...,Match Report,NaN,10.0,3.0,17.0,0.0,0.0,0.0,2021,Sheffield United
1387,41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0.0,1.0,...,Match Report,NaN,11.0,1.0,16.0,1.0,0.0,0.0,2021,Sheffield United


In [7]:
selected_fields = [
    'date', 
    'venue', 
    'result', 
    'gf', 
    'ga', 
    'opponent', 
    'xg', 
    'xga', 
    'poss', 
    'formation', 
    'sh', 
    'sot', 
    'dist', 
    'fk', 
    'pk', 
    'team'
]

# Create a new DataFrame with the selected fields
new_table = x[selected_fields]

# Save the new DataFrame to a new CSV file
new_table.to_csv('filtered_data.csv', index=False)


In [9]:
new_table

,date,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,dist,fk,pk,team
0,2021-08-15,Away,L,0.0,1.0,Tottenham,1.9,1.3,64.0,4-3-3,18.0,4.0,16.9,1.0,0.0,Manchester City
1,2021-08-21,Home,W,5.0,0.0,Norwich City,2.7,0.1,67.0,4-3-3,16.0,4.0,17.3,1.0,0.0,Manchester City
2,2021-08-28,Home,W,5.0,0.0,Arsenal,3.8,0.1,80.0,4-3-3,25.0,10.0,14.3,0.0,0.0,Manchester City
3,2021-09-11,Away,W,1.0,0.0,Leicester City,2.9,0.8,61.0,4-3-3,25.0,8.0,14.0,0.0,0.0,Manchester City
4,2021-09-18,Home,D,0.0,0.0,Southampton,1.1,0.4,63.0,4-3-3,16.0,1.0,15.7,1.0,0.0,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384,2021-05-02,Away,L,0.0,4.0,Tottenham,0.5,2.0,34.0,3-4-1-2,8.0,1.0,17.4,0.0,0.0,Sheffield United
1385,2021-05-08,Home,L,0.0,2.0,Crystal Palace,0.7,2.1,50.0,3-5-2,7.0,0.0,11.4,1.0,0.0,Sheffield United
1386,2021-05-16,Away,W,1.0,0.0,Everton,1.6,1.3,38.0,3-4-3,10.0,3.0,17.0,0.0,0.0,Sheffield United
1387,2021-05-19,Away,L,0.0,1.0,Newcastle Utd,0.8,1.5,50.0,3-4-3,11.0,1.0,16.0,1.0,0.0,Sheffield United


In [11]:
new_table.dtypes


date          object
venue         object
result        object
gf           float64
ga           float64
opponent      object
xg           float64
xga          float64
poss         float64
formation     object
sh           float64
sot          float64
dist         float64
fk           float64
pk           float64
team          object
dtype: object

In [13]:
# Example: Check rows where 'gf' or 'xg' is NaN
missing_specific = new_table[new_table['dist'].isna()]
print(missing_specific)

            date venue result   gf   ga  opponent   xg  xga  poss formation  \
1127  2020-10-18  Home      D  1.0  1.0  Brighton  0.8  1.1  34.0     4-4-2   

       sh  sot  dist   fk   pk            team  
1127  0.0  0.0   NaN  0.0  1.0  Crystal Palace  


In [15]:
new_table['dist'] = new_table['dist'].fillna(25)

print(new_table.loc[1127])  # Verify the update for the specific row

date             2020-10-18
venue                  Home
result                    D
gf                      1.0
ga                      1.0
opponent           Brighton
xg                      0.8
xga                     1.1
poss                   34.0
formation             4-4-2
sh                      0.0
sot                     0.0
dist                   25.0
fk                      0.0
pk                      1.0
team         Crystal Palace
Name: 1127, dtype: object


C:\Users\HP\AppData\Local\Temp\ipykernel_4864\4121539467.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_table['dist'] = new_table['dist'].fillna(25)


In [17]:
new_table.isna().sum()


date         0
venue        0
result       0
gf           0
ga           0
opponent     0
xg           0
xga          0
poss         0
formation    0
sh           0
sot          0
dist         0
fk           0
pk           0
team         0
dtype: int64

In [19]:
new_table.head(2)

,date,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,dist,fk,pk,team
0,2021-08-15,Away,L,0.0,1.0,Tottenham,1.9,1.3,64.0,4-3-3,18.0,4.0,16.9,1.0,0.0,Manchester City
1,2021-08-21,Home,W,5.0,0.0,Norwich City,2.7,0.1,67.0,4-3-3,16.0,4.0,17.3,1.0,0.0,Manchester City


In [21]:
#win and loss
table1=new_table[['venue','result','team','opponent']]
table1

,venue,result,team,opponent
0,Away,L,Manchester City,Tottenham
1,Home,W,Manchester City,Norwich City
2,Home,W,Manchester City,Arsenal
3,Away,W,Manchester City,Leicester City
4,Home,D,Manchester City,Southampton
...,...,...,...,...
1384,Away,L,Sheffield United,Tottenham
1385,Home,L,Sheffield United,Crystal Palace
1386,Away,W,Sheffield United,Everton
1387,Away,L,Sheffield United,Newcastle Utd


In [181]:
all_teams = pd.concat([table1['opponent'],table1['team']])

In [183]:
all_teams.unique()

array(['Tottenham', 'Norwich City', 'Arsenal', 'Leicester City',
       'Southampton', 'Chelsea', 'Liverpool', 'Burnley', 'Brighton',
       'Crystal Palace', 'Manchester Utd', 'Everton', 'West Ham',
       'Aston Villa', 'Watford', 'Wolves', 'Leeds United',
       'Newcastle Utd', 'Brentford', 'Manchester City', 'Sheffield Utd',
       'Fulham', 'West Brom', 'Tottenham Hotspur', 'Manchester United',
       'West Ham United', 'Wolverhampton Wanderers', 'Newcastle United',
       'Brighton and Hove Albion', 'West Bromwich Albion',
       'Sheffield United'], dtype=object)

In [185]:
from sklearn.preprocessing import LabelEncoder

In [187]:
merged_table1=LabelEncoder()

In [189]:
merged_table1.fit(all_teams)

LabelEncoder()

In [191]:
table1['opp']=merged_table1.transform(table1['opponent'])

C:\Users\HP\AppData\Local\Temp\ipykernel_4864\2396343956.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table1['opp']=merged_table1.transform(table1['opponent'])


In [193]:
table1['teams']=merged_table1.transform(table1['team'])

C:\Users\HP\AppData\Local\Temp\ipykernel_4864\3056371834.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table1['teams']=merged_table1.transform(table1['team'])


In [195]:
table1

,venue,result,team,opponent,opp,teams
0,Away,L,Manchester City,Tottenham,22,13
1,Home,W,Manchester City,Norwich City,18,13
2,Home,W,Manchester City,Arsenal,0,13
3,Away,W,Manchester City,Leicester City,11,13
4,Home,D,Manchester City,Southampton,21,13
...,...,...,...,...,...,...
1384,Away,L,Sheffield United,Tottenham,22,19
1385,Home,L,Sheffield United,Crystal Palace,7,19
1386,Away,W,Sheffield United,Everton,8,19
1387,Away,L,Sheffield United,Newcastle Utd,17,19


In [199]:
merge =LabelEncoder()

In [201]:
merge.fit(table1['result'])

LabelEncoder()

In [203]:
table1['results']=merge.transform(table1['result'])

C:\Users\HP\AppData\Local\Temp\ipykernel_4864\3910834077.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table1['results']=merge.transform(table1['result'])


In [205]:
dum = LabelEncoder()

In [207]:
dum.fit(table1['venue'])

LabelEncoder()

In [209]:
table1['venues']=dum.transform(table1['venue'])

C:\Users\HP\AppData\Local\Temp\ipykernel_4864\3467307879.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table1['venues']=dum.transform(table1['venue'])


In [211]:
table1

,venue,result,team,opponent,opp,teams,results,venues
0,Away,L,Manchester City,Tottenham,22,13,1,0
1,Home,W,Manchester City,Norwich City,18,13,2,1
2,Home,W,Manchester City,Arsenal,0,13,2,1
3,Away,W,Manchester City,Leicester City,11,13,2,0
4,Home,D,Manchester City,Southampton,21,13,0,1
...,...,...,...,...,...,...,...,...
1384,Away,L,Sheffield United,Tottenham,22,19,1,0
1385,Home,L,Sheffield United,Crystal Palace,7,19,1,1
1386,Away,W,Sheffield United,Everton,8,19,2,0
1387,Away,L,Sheffield United,Newcastle Utd,17,19,1,0


In [215]:
#prepare for training
table_x=table1.drop(['venue','result','opponent','team','results'],axis=1)

In [217]:
table_y =table1.results

In [219]:
from sklearn.model_selection import train_test_split

In [221]:
from sklearn.linear_model import LogisticRegression

In [223]:
from sklearn.model_selection import cross_val_score

In [225]:
from sklearn.svm import SVC

In [227]:
from sklearn.ensemble import RandomForestClassifier

In [229]:
from sklearn import tree

In [233]:
table_lg=cross_val_score(LogisticRegression(),table_x,table_y)

In [257]:
table_lg.mean()

0.3815858504532114

In [237]:
table_sv = cross_val_score(SVC(),table_x,table_y)

In [259]:
table_sv.mean()

0.4038880087265927

In [241]:
table_rf=cross_val_score(RandomForestClassifier(),table_x,table_y)

In [261]:
table_rf.mean()

0.388764511856219

In [245]:
table_dt =cross_val_score(tree.DecisionTreeClassifier(),table_x,table_y)

In [263]:
table_dt.mean()

0.3808300651897255

In [249]:
train_xdata,test_xdata,train_ydata,test_ydata=train_test_split(table_x,table_y,test_size=.2)

In [265]:
model_res=SVC()

In [267]:
model_res.fit(train_xdata,train_ydata)

SVC()

In [269]:
model_res.score(test_xdata,test_ydata)

0.38848920863309355

In [279]:
model_res.predict(test_xdata)

array([1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1,
       2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2,
       2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1,
       1, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1])

In [271]:
#model saving
import joblib

In [273]:
joblib.dump(model_res,'winning-result')

['winning-result']

In [275]:
#model loading and checking
n=joblib.load('winning-result')

In [277]:
n.predict([[0,16,18]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1])

In [35]:
new_table.head()

,date,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,dist,fk,pk,team
0,2021-08-15,Away,L,0.0,1.0,Tottenham,1.9,1.3,64.0,4-3-3,18.0,4.0,16.9,1.0,0.0,Manchester City
1,2021-08-21,Home,W,5.0,0.0,Norwich City,2.7,0.1,67.0,4-3-3,16.0,4.0,17.3,1.0,0.0,Manchester City
2,2021-08-28,Home,W,5.0,0.0,Arsenal,3.8,0.1,80.0,4-3-3,25.0,10.0,14.3,0.0,0.0,Manchester City
3,2021-09-11,Away,W,1.0,0.0,Leicester City,2.9,0.8,61.0,4-3-3,25.0,8.0,14.0,0.0,0.0,Manchester City
4,2021-09-18,Home,D,0.0,0.0,Southampton,1.1,0.4,63.0,4-3-3,16.0,1.0,15.7,1.0,0.0,Manchester City


In [43]:
new_table['opp_pos']=new_table['poss'].apply(lambda x:float(100-x))

C:\Users\HP\AppData\Local\Temp\ipykernel_4864\3954964578.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_table['opp_pos']=new_table['poss'].apply(lambda x:float(100-x))


In [45]:
new_table.head(2)

,date,venue,result,gf,ga,opponent,xg,xga,poss,formation,sh,sot,dist,fk,pk,team,opp_pos
0,2021-08-15,Away,L,0.0,1.0,Tottenham,1.9,1.3,64.0,4-3-3,18.0,4.0,16.9,1.0,0.0,Manchester City,36.0
1,2021-08-21,Home,W,5.0,0.0,Norwich City,2.7,0.1,67.0,4-3-3,16.0,4.0,17.3,1.0,0.0,Manchester City,33.0


In [47]:
#position of teams
team_data_pos=new_table[['venue','result','opponent','team','poss','opp_pos']]

In [49]:
team_data_pos

,venue,result,opponent,team,poss,opp_pos
0,Away,L,Tottenham,Manchester City,64.0,36.0
1,Home,W,Norwich City,Manchester City,67.0,33.0
2,Home,W,Arsenal,Manchester City,80.0,20.0
3,Away,W,Leicester City,Manchester City,61.0,39.0
4,Home,D,Southampton,Manchester City,63.0,37.0
...,...,...,...,...,...,...
1384,Away,L,Tottenham,Sheffield United,34.0,66.0
1385,Home,L,Crystal Palace,Sheffield United,50.0,50.0
1386,Away,W,Everton,Sheffield United,38.0,62.0
1387,Away,L,Newcastle Utd,Sheffield United,50.0,50.0


In [57]:
team_data_pos['opponent'].unique()

array(['Tottenham', 'Norwich City', 'Arsenal', 'Leicester City',
       'Southampton', 'Chelsea', 'Liverpool', 'Burnley', 'Brighton',
       'Crystal Palace', 'Manchester Utd', 'Everton', 'West Ham',
       'Aston Villa', 'Watford', 'Wolves', 'Leeds United',
       'Newcastle Utd', 'Brentford', 'Manchester City', 'Sheffield Utd',
       'Fulham', 'West Brom'], dtype=object)

In [59]:
all_teams = pd.concat([team_data_pos['opponent'],team_data_pos['team']])

In [61]:
all_teams.unique()

array(['Tottenham', 'Norwich City', 'Arsenal', 'Leicester City',
       'Southampton', 'Chelsea', 'Liverpool', 'Burnley', 'Brighton',
       'Crystal Palace', 'Manchester Utd', 'Everton', 'West Ham',
       'Aston Villa', 'Watford', 'Wolves', 'Leeds United',
       'Newcastle Utd', 'Brentford', 'Manchester City', 'Sheffield Utd',
       'Fulham', 'West Brom', 'Tottenham Hotspur', 'Manchester United',
       'West Ham United', 'Wolverhampton Wanderers', 'Newcastle United',
       'Brighton and Hove Albion', 'West Bromwich Albion',
       'Sheffield United'], dtype=object)

In [63]:
from sklearn.preprocessing import LabelEncoder


In [65]:
labelen=LabelEncoder()

In [67]:
labelen.fit(all_teams)

LabelEncoder()

In [69]:
team_data_pos['opp']=labelen.transform(team_data_pos['opponent'])

C:\Users\HP\AppData\Local\Temp\ipykernel_4864\1664922980.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_data_pos['opp']=labelen.transform(team_data_pos['opponent'])


In [71]:
team_data_pos

,venue,result,opponent,team,poss,opp_pos,opp
0,Away,L,Tottenham,Manchester City,64.0,36.0,22
1,Home,W,Norwich City,Manchester City,67.0,33.0,18
2,Home,W,Arsenal,Manchester City,80.0,20.0,0
3,Away,W,Leicester City,Manchester City,61.0,39.0,11
4,Home,D,Southampton,Manchester City,63.0,37.0,21
...,...,...,...,...,...,...,...
1384,Away,L,Tottenham,Sheffield United,34.0,66.0,22
1385,Home,L,Crystal Palace,Sheffield United,50.0,50.0,7
1386,Away,W,Everton,Sheffield United,38.0,62.0,8
1387,Away,L,Newcastle Utd,Sheffield United,50.0,50.0,17


In [73]:
team_data_pos['team_en']=labelen.transform(team_data_pos['team'])

C:\Users\HP\AppData\Local\Temp\ipykernel_4864\179674872.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_data_pos['team_en']=labelen.transform(team_data_pos['team'])


In [75]:
labelent=LabelEncoder()

In [81]:
labelent.fit(team_data_pos['result'])

LabelEncoder()

In [83]:
team_data_pos['res']=labelent.transform(team_data_pos['result'])

C:\Users\HP\AppData\Local\Temp\ipykernel_4864\3886355701.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_data_pos['res']=labelent.transform(team_data_pos['result'])


In [95]:
labelv=LabelEncoder()

In [97]:
labelv.fit(team_data_pos['venue'])

LabelEncoder()

In [99]:
team_data_pos['venue_d']=labelv.transform(team_data_pos['venue'])

C:\Users\HP\AppData\Local\Temp\ipykernel_4864\2446182875.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_data_pos['venue_d']=labelv.transform(team_data_pos['venue'])


In [101]:
team_data_pos

,venue,result,opponent,team,poss,opp_pos,opp,team_en,res,venue_d
0,Away,L,Tottenham,Manchester City,64.0,36.0,22,13,1,0
1,Home,W,Norwich City,Manchester City,67.0,33.0,18,13,2,1
2,Home,W,Arsenal,Manchester City,80.0,20.0,0,13,2,1
3,Away,W,Leicester City,Manchester City,61.0,39.0,11,13,2,0
4,Home,D,Southampton,Manchester City,63.0,37.0,21,13,0,1
...,...,...,...,...,...,...,...,...,...,...
1384,Away,L,Tottenham,Sheffield United,34.0,66.0,22,19,1,0
1385,Home,L,Crystal Palace,Sheffield United,50.0,50.0,7,19,1,1
1386,Away,W,Everton,Sheffield United,38.0,62.0,8,19,2,0
1387,Away,L,Newcastle Utd,Sheffield United,50.0,50.0,17,19,1,0


In [105]:
#team pos final data
team_final = team_data_pos.drop(['venue','result','opponent','team'],axis=1)

In [107]:
team_final

,poss,opp_pos,opp,team_en,res,venue_d
0,64.0,36.0,22,13,1,0
1,67.0,33.0,18,13,2,1
2,80.0,20.0,0,13,2,1
3,61.0,39.0,11,13,2,0
4,63.0,37.0,21,13,0,1
...,...,...,...,...,...,...
1384,34.0,66.0,22,19,1,0
1385,50.0,50.0,7,19,1,1
1386,38.0,62.0,8,19,2,0
1387,50.0,50.0,17,19,1,0


In [111]:
#preparinfg for training
team_model_data = team_final.drop('poss',axis=1)

In [113]:
team_model_data

,opp_pos,opp,team_en,res,venue_d
0,36.0,22,13,1,0
1,33.0,18,13,2,1
2,20.0,0,13,2,1
3,39.0,11,13,2,0
4,37.0,21,13,0,1
...,...,...,...,...,...
1384,66.0,22,19,1,0
1385,50.0,7,19,1,1
1386,62.0,8,19,2,0
1387,50.0,17,19,1,0


In [115]:
team_y =team_final.poss

In [117]:
team_y

0       64.0
1       67.0
2       80.0
3       61.0
4       63.0
        ... 
1384    34.0
1385    50.0
1386    38.0
1387    50.0
1388    41.0
Name: poss, Length: 1389, dtype: float64

In [121]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC


In [123]:
team_lg_score =cross_val_score(LogisticRegression(),team_model_data,team_y)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modu

In [125]:
team_lg_score

array([0.04316547, 0.05395683, 0.05035971, 0.0647482 , 0.05054152])

In [127]:
team_rf_score =cross_val_score(RandomForestClassifier(),team_model_data,team_y)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


In [129]:
team_rf_score

array([0.65107914, 0.67985612, 0.68345324, 0.70863309, 0.71119134])

In [131]:
team_sv_score =cross_val_score(SVC(),team_model_data,team_y)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


In [133]:
team_sv_score

array([0.0971223 , 0.10071942, 0.08992806, 0.10071942, 0.12274368])

In [135]:
team_dt_score =cross_val_score(tree.DecisionTreeClassifier(),team_model_data,team_y)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


In [137]:
team_dt_score

array([0.99280576, 0.98920863, 0.99640288, 0.99280576, 0.99277978])

In [141]:
from sklearn.model_selection import train_test_split

In [143]:
team_dt_model = tree.DecisionTreeClassifier()

In [145]:
trainX,testX,trainY,testY=train_test_split(team_model_data,team_y,test_size=.2)

In [147]:
team_dt_model.fit(trainX,trainY)

DecisionTreeClassifier()

In [149]:
team_dt_model.score(testX,testY)

0.9964028776978417

In [151]:
team_dt_model.predict(testX)

array([34., 59., 61., 54., 46., 35., 52., 43., 67., 29., 37., 52., 53.,
       59., 47., 69., 51., 33., 25., 52., 54., 57., 59., 26., 48., 40.,
       47., 40., 38., 33., 46., 33., 50., 47., 58., 58., 55., 57., 57.,
       76., 43., 51., 49., 36., 65., 44., 50., 73., 47., 52., 49., 49.,
       52., 51., 44., 42., 66., 49., 47., 52., 41., 59., 31., 38., 65.,
       59., 35., 68., 53., 43., 56., 51., 65., 61., 68., 49., 63., 53.,
       39., 55., 35., 48., 48., 43., 32., 60., 46., 42., 50., 46., 52.,
       64., 31., 66., 45., 55., 51., 29., 50., 45., 31., 54., 42., 40.,
       68., 28., 40., 65., 33., 65., 44., 69., 42., 41., 55., 58., 57.,
       74., 33., 39., 53., 28., 29., 45., 57., 49., 34., 68., 65., 24.,
       19., 42., 55., 52., 66., 53., 62., 42., 45., 72., 48., 69., 67.,
       60., 36., 42., 50., 55., 39., 58., 40., 67., 34., 65., 68., 48.,
       47., 69., 58., 26., 63., 42., 62., 61., 44., 61., 62., 61., 53.,
       47., 66., 53., 43., 48., 43., 51., 37., 48., 42., 53., 47

In [153]:
team_dt_model.predict([[50,17,19,1,0]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([50.])

In [155]:
import joblib

In [157]:
joblib.dump(team_dt_model,'team_position')

['team_position']

In [163]:
#find oppositional position
opp_dta=team_final.drop('opp_pos',axis=1)

In [165]:
opp_y =team_final['opp_pos']

In [167]:
opp_pos_model =tree.DecisionTreeClassifier()

In [169]:
train_x,test_x,train_y,test_y =train_test_split(opp_dta,opp_y,test_size=.2)

In [171]:
opp_pos_model.fit(train_x,train_y)

DecisionTreeClassifier()

In [173]:
opp_pos_model.score(test_x,test_y)

0.9892086330935251

In [177]:
opp_pos_model.predict([[50,17,19,1,0]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([50.])

In [179]:
joblib.dump(opp_pos_model,'oppositional_position')

['oppositional_position']